// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DauAnNganNam.Models;

public partial class Image
{
    public int ImageId { get; set; }

    public string ImageUrl { get; set; }

    public int? ProductId { get; set; }

    public int NewsId { get; set; }

    public virtual News News { get; set; }

    public virtual Product Product { get; set; }
}