// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DauAnNganNam.Models;

public partial class News
{
    public int NewsId { get; set; }

    public string Title { get; set; }

    public string Summary { get; set; }

    public string Content { get; set; }

    public DateOnly? CreateDate { get; set; }

    public DateOnly? UpdateDate { get; set; }

    public int? CreateById { get; set; }

    public int? UpdateById { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDelete { get; set; }

    public virtual Account CreateBy { get; set; }

    public virtual ICollection<Image> Images { get; set; } = new List<Image>();
}