name: Cleanup Old Artifacts

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      age:
        description: 'Delete artifacts older than this age (e.g., 1d, 2w, 6M, 1y)'
        required: true
        default: '0d' # 0d will delete all artifacts

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: ${{ github.event.inputs.age }}